# Generated by Django 4.0.3 on 2022-04-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_id',
            new_name='address',
        ),
    ]
